// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneyManager.API.Data.Services.Context;

namespace MoneyManager.API.Data.Services.Migrations
{
    [DbContext(typeof(MoneyManagerContext))]
    [Migration("20181207072403_MoneyManagerMigration")]
    partial class MoneyManagerMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MoneyManager.API.Data.DepositDetails", b =>
                {
                    b.Property<int>("depositId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("depositAmount")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 38, scale: 17)))
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("depositDate");

                    b.Property<string>("depositSource")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.HasKey("depositId");

                    b.ToTable("DepositDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
