// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneyManager.API.Data.Services.SeriesManagerDataContext;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MoneyManager.API.Data.Services.Migrations.SeriesManager
{
    [DbContext(typeof(SeriesManagerContext))]
    [Migration("20190302072315_SeriesManagerMigr")]
    partial class SeriesManagerMigr
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MoneyManager.API.Data.SeriesManagerData.Comics", b =>
                {
                    b.Property<long>("ComicsId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ComicsName")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.HasKey("ComicsId");

                    b.ToTable("Comics");

                    b.HasData(
                        new { ComicsId = 1L, ComicsName = "Doomsday Clock" },
                        new { ComicsId = 2L, ComicsName = "The Life of Captain Marvel" },
                        new { ComicsId = 3L, ComicsName = "Tony Stark Iron Man" },
                        new { ComicsId = 4L, ComicsName = "Spider-geddon" }
                    );
                });

            modelBuilder.Entity("MoneyManager.API.Data.SeriesManagerData.Series", b =>
                {
                    b.Property<long>("SeriesId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("ApiId");

                    b.Property<string>("SeriesName")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.HasKey("SeriesId");

                    b.ToTable("Series");

                    b.HasData(
                        new { SeriesId = 1L, ApiId = 7194L, SeriesName = "13 Reasons Why" },
                        new { SeriesId = 2L, ApiId = 31339L, SeriesName = "A Discovery of Witches" },
                        new { SeriesId = 3L, ApiId = 3949L, SeriesName = "A series of unfortunate events" },
                        new { SeriesId = 4L, ApiId = 31L, SeriesName = "Agents of S.H.I.E.L.D." },
                        new { SeriesId = 5L, ApiId = 12036L, SeriesName = "Altered Carbon" },
                        new { SeriesId = 6L, ApiId = 3182L, SeriesName = "American Gods" },
                        new { SeriesId = 7L, ApiId = 4L, SeriesName = "Arrow" },
                        new { SeriesId = 8L, ApiId = 919L, SeriesName = "Attack on Titan" },
                        new { SeriesId = 9L, ApiId = 2540L, SeriesName = "Avengers Assemble" },
                        new { SeriesId = 10L, ApiId = 22084L, SeriesName = "Ben 10" },
                        new { SeriesId = 11L, ApiId = 21142L, SeriesName = "Big Hero 6 The Series" },
                        new { SeriesId = 12L, ApiId = 20683L, SeriesName = "Black Lightning" },
                        new { SeriesId = 13L, ApiId = 57L, SeriesName = "Blackish" },
                        new { SeriesId = 14L, ApiId = 1855L, SeriesName = "Blindspot" },
                        new { SeriesId = 15L, ApiId = 49L, SeriesName = "Brooklyn Nine-Nine" },
                        new { SeriesId = 16L, ApiId = 25414L, SeriesName = "Castle Rock" },
                        new { SeriesId = 17L, ApiId = 25242L, SeriesName = "Castlevania" },
                        new { SeriesId = 18L, ApiId = 15307L, SeriesName = "Cloak and Dagger" },
                        new { SeriesId = 19L, ApiId = 25110L, SeriesName = "Condor" },
                        new { SeriesId = 20L, ApiId = 15L, SeriesName = "Constantine" },
                        new { SeriesId = 21L, ApiId = 1369L, SeriesName = "Daredevil" },
                        new { SeriesId = 22L, ApiId = 1851L, SeriesName = "Dcs Legends of Tomorrow" },
                        new { SeriesId = 23L, ApiId = 210L, SeriesName = "Doctor Who" },
                        new { SeriesId = 24L, ApiId = 2368L, SeriesName = "Dragon Ball Super" },
                        new { SeriesId = 25L, ApiId = 133L, SeriesName = "Elementary" },
                        new { SeriesId = 26L, ApiId = 1824L, SeriesName = "Fear The Walking Dead" },
                        new { SeriesId = 27L, ApiId = 23314L, SeriesName = "Final Space" },
                        new { SeriesId = 28L, ApiId = 20003L, SeriesName = "Freedom Fighters The Ray" },
                        new { SeriesId = 29L, ApiId = 3022L, SeriesName = "Future Man" },
                        new { SeriesId = 30L, ApiId = 82L, SeriesName = "Game of Thrones" },
                        new { SeriesId = 31L, ApiId = 31257L, SeriesName = "God Friended Me" },
                        new { SeriesId = 32L, ApiId = 11L, SeriesName = "Gotham" },
                        new { SeriesId = 33L, ApiId = 28366L, SeriesName = "Grown-ish" },
                        new { SeriesId = 34L, ApiId = 2476L, SeriesName = "Guardians of the Galaxy" },
                        new { SeriesId = 35L, ApiId = 21216L, SeriesName = "Happy" },
                        new { SeriesId = 36L, ApiId = 36768L, SeriesName = "Happy Together" },
                        new { SeriesId = 37L, ApiId = 7L, SeriesName = "Homeland" },
                        new { SeriesId = 38L, ApiId = 2300L, SeriesName = "Into The Badlands" },
                        new { SeriesId = 39L, ApiId = 2175L, SeriesName = "Iron Fist" },
                        new { SeriesId = 40L, ApiId = 1589L, SeriesName = "iZombie" },
                        new { SeriesId = 41L, ApiId = 1370L, SeriesName = "Jessica Jones" },
                        new { SeriesId = 42L, ApiId = 12522L, SeriesName = "Justice League Action" },
                        new { SeriesId = 43L, ApiId = 11918L, SeriesName = "Kong King of the Apes" },
                        new { SeriesId = 44L, ApiId = 3082L, SeriesName = "Krypton" },
                        new { SeriesId = 45L, ApiId = 41L, SeriesName = "Last Man Standing" },
                        new { SeriesId = 46L, ApiId = 6393L, SeriesName = "Legion" },
                        new { SeriesId = 47L, ApiId = 5495L, SeriesName = "Lethal Weapon" },
                        new { SeriesId = 48L, ApiId = 8898L, SeriesName = "Lost in Space" },
                        new { SeriesId = 49L, ApiId = 1859L, SeriesName = "Lucifer" },
                        new { SeriesId = 50L, ApiId = 2174L, SeriesName = "Luke Cage" },
                        new { SeriesId = 51L, ApiId = 5511L, SeriesName = "MacGyver" },
                        new { SeriesId = 52L, ApiId = 32819L, SeriesName = "Magnum P I" },
                        new { SeriesId = 53L, ApiId = 12888L, SeriesName = "Man with a plan" },
                        new { SeriesId = 54L, ApiId = 31365L, SeriesName = "Manifest" },
                        new { SeriesId = 55L, ApiId = 2176L, SeriesName = "Marvels The Defenders" },
                        new { SeriesId = 56L, ApiId = 324L, SeriesName = "Masterchef" },
                        new { SeriesId = 57L, ApiId = 3160L, SeriesName = "MasterChef Australia" },
                        new { SeriesId = 58L, ApiId = 417L, SeriesName = "MasterChef Junior" },
                        new { SeriesId = 59L, ApiId = 80L, SeriesName = "Modern Family" },
                        new { SeriesId = 60L, ApiId = 1871L, SeriesName = "Mr Robot" },
                        new { SeriesId = 61L, ApiId = 488L, SeriesName = "Naruto Shippuden" },
                        new { SeriesId = 62L, ApiId = 590L, SeriesName = "Pokemon" },
                        new { SeriesId = 63L, ApiId = 3144L, SeriesName = "Preacher" },
                        new { SeriesId = 64L, ApiId = 216L, SeriesName = "Rick and Morty" },
                        new { SeriesId = 65L, ApiId = 34300L, SeriesName = "Rise of the Teenage Mutant Ninja Turtles" },
                        new { SeriesId = 66L, ApiId = 5262L, SeriesName = "Riverdale" },
                        new { SeriesId = 67L, ApiId = 37920L, SeriesName = "Runaways" },
                        new { SeriesId = 68L, ApiId = 22188L, SeriesName = "Salvation" },
                        new { SeriesId = 69L, ApiId = 14612L, SeriesName = "Santa Clarita Diet" },
                        new { SeriesId = 70L, ApiId = 2158L, SeriesName = "Shadowhunters" },
                        new { SeriesId = 71L, ApiId = 335L, SeriesName = "Sherlock" },
                        new { SeriesId = 72L, ApiId = 143L, SeriesName = "Silicon Valley" },
                        new { SeriesId = 73L, ApiId = 1611L, SeriesName = "Spider-Man" },
                        new { SeriesId = 74L, ApiId = 713L, SeriesName = "SpongeBob SquarePants" },
                        new { SeriesId = 75L, ApiId = 7480L, SeriesName = "Star Trek Discovery" },
                        new { SeriesId = 76L, ApiId = 36483L, SeriesName = "Star Wars Resistance" },
                        new { SeriesId = 77L, ApiId = 2993L, SeriesName = "Stranger things" },
                        new { SeriesId = 78L, ApiId = 17862L, SeriesName = "Stretch Armstrong and the Flex Fighters" },
                        new { SeriesId = 79L, ApiId = 1850L, SeriesName = "Supergirl" },
                        new { SeriesId = 80L, ApiId = 19L, SeriesName = "Supernatural" },
                        new { SeriesId = 81L, ApiId = 33395L, SeriesName = "Take Two" },
                        new { SeriesId = 82L, ApiId = 6L, SeriesName = "The 100" },
                        new { SeriesId = 83L, ApiId = 34017L, SeriesName = "The Adventures of Kid Danger" },
                        new { SeriesId = 84L, ApiId = 66L, SeriesName = "The Big Bang Theory" },
                        new { SeriesId = 85L, ApiId = 37675L, SeriesName = "The Dragon Prince" },
                        new { SeriesId = 86L, ApiId = 36449L, SeriesName = "The Epic Tales of Captain Underpants" },
                        new { SeriesId = 87L, ApiId = 13L, SeriesName = "The Flash" },
                        new { SeriesId = 88L, ApiId = 25948L, SeriesName = "The Gifted" },
                        new { SeriesId = 89L, ApiId = 17078L, SeriesName = "The Grand Tour" },
                        new { SeriesId = 90L, ApiId = 35839L, SeriesName = "The Neighborhood" },
                        new { SeriesId = 91L, ApiId = 20263L, SeriesName = "The Orville" },
                        new { SeriesId = 92L, ApiId = 16544L, SeriesName = "The Punisher" },
                        new { SeriesId = 93L, ApiId = 28134L, SeriesName = "The Purge" },
                        new { SeriesId = 94L, ApiId = 32938L, SeriesName = "The Rookie" },
                        new { SeriesId = 95L, ApiId = 14116L, SeriesName = "The Tick" },
                        new { SeriesId = 96L, ApiId = 4296L, SeriesName = "The Tom and Jerry Show" },
                        new { SeriesId = 97L, ApiId = 73L, SeriesName = "The Walking Dead" },
                        new { SeriesId = 98L, ApiId = 1878L, SeriesName = "Thunderbirds are go" },
                        new { SeriesId = 99L, ApiId = 8873L, SeriesName = "Timeless " },
                        new { SeriesId = 100L, ApiId = 27557L, SeriesName = "Titans" },
                        new { SeriesId = 101L, ApiId = 38387L, SeriesName = "Transformers Cyberverse" },
                        new { SeriesId = 102L, ApiId = 7523L, SeriesName = "Van Helsing" },
                        new { SeriesId = 103L, ApiId = 15296L, SeriesName = "Voltron Legendary Defender" },
                        new { SeriesId = 104L, ApiId = 1371L, SeriesName = "Westworld" },
                        new { SeriesId = 105L, ApiId = 689L, SeriesName = "Young Justice" },
                        new { SeriesId = 106L, ApiId = 26020L, SeriesName = "Young Sheldon" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
